import Navbar from "@/components/navbar";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ProviderRedux from "./provider";
import UserMessage from "./UserMessage";
import ComapnyMessage from "./CompanyMessage";
import JobMessage from "./JobMessage";

export const metadata = {
  title: "Hireheaven",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ProviderRedux>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <UserMessage />
            <ComapnyMessage />
            <JobMessage />
          </ThemeProvider>
        </ProviderRedux>
      </body>
    </html>
  );
}
